Make drawer links hoverable and focusable
etesync/etesync-notes pull request #100
Opened 2021-01-12 15:51 UTC by zecakeh

This starts the work on #87 and #88.

This PR includes:
- A new `Anchor` component that is an improvement from the `Link` element from React Navigation because it is styled according to its focused and hovered state. It is also usable natively in the `Drawer` (`Link` needs a small hack to work where the navigation context is not available). It should only be used on web.
- A new `ListItem` component that uses the `Anchor` and should replace all the `List.Item` elements that have an `onPress`.
- Type declarations for the components I used in `react-native-web` because none are available
- The `Drawer` with the new `ListItem`s. Hovered/focused styles only work on items with links right now. A future PR should add that for the others.

Tested on web Firefox Linux
Tested on native Android

2021-01-12 15:59 UTC, tasn requested changes
I gotta say, this whole PR feels a bit wrong and too involved for me. I mean, the issue seems to be that react-native-paper (or react-native-web?) isn't using anchor tags when it should, right? Well, why not just add a `.web.tsx` file (or whatever the expo convention is) and just wrap it with real anchor tags on the web? Or alternatively, have this ListItem be a very think wrapper around List.Item that just adds a real anchor tab on the web?

2021-01-12 15:59 UTC, tasn commented on src/widgets/Anchor.tsx
> +    return <>children</>;
This doesn't look like it would run on Android.

2021-01-13 16:43 UTC, zecakeh commented
I tried with DrawerItem now. I wrapped it in a Pressable just to have the focused and hovered styling. I had to hack a bit the styles to make it look like before.
The good news is, it does work out of the box with DrawerItem that are not links too.
I'd still need to implement the disabled state that's used by the logout button, but that's easy.
The text color is also a bit different than List.Item because React Native Paper changes a bit the theme text color before applying it.

2021-01-25 21:05 UTC, zecakeh commented
Managing hovered and focused state is not yet easily doable, so for now this PR will just show a pointer and the link url on hover in the drawer in web browsers.

2021-02-05 11:43 UTC, tasn commented
Looks much better! Fix the conflicts and this can be merged!

2021-02-05 14:03 UTC, zecakeh commented
Actually I'll had hovered and focused state if I manage to do it for List Items

2021-02-05 14:30 UTC, tasn commented
Not sure I understand what you are referring to.

2021-02-05 17:09 UTC, zecakeh commented
If I manage to add CSS hovered and focused state to #142, I can add it here too

2021-02-05 19:42 UTC, zecakeh commented
Rebased and ready to merge

2021-02-07 08:11 UTC, merged