Add possibility to change a note's collection
etesync/etesync-notes pull request #120
Opened 2021-01-21 13:47 UTC by zecakeh

… aka move notes.

In practice: copy the item into another collection and delete the old one.

This fixes #112.

Tested on web Firefox Linux
Tested on native Android

2021-01-21 13:50 UTC, tasn requested changes
I'd rather have it as an explicit move operation rather than just being able to change the collection and have this done, as it has non-obvious implications for now (the fact that it's deleted and a new one is created).

2021-01-21 13:50 UTC, tasn commented on src/screens/NoteListScreen.tsx
> +  console.log("colUid", colUid);
:thinking:

2021-01-21 15:02 UTC, zecakeh commented on src/screens/NoteListScreen.tsx
> +  console.log("colUid", colUid);
Sorry 😅

2021-01-21 15:52 UTC, zecakeh commented
I created a new screen to move the notes, I don't know if that's what you had in mind.

2021-02-21 17:06 UTC, tasn commented
Yeah, that's what I had in mind! :)

2021-02-21 17:06 UTC, merged